version: '3.8'
name: 'billing'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: leal
      MONGO_INITDB_ROOT_PASSWORD: leal
    volumes:
      - ~/docker:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: ["--auth", "--bind_ip_all"]

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    volumes:
      - ./seq-dev:/data 
